First PR From Dev to Main
2103-USD/tech-phantoms pull request #11
Opened 2021-08-19 03:52 UTC by captnjak

2021-08-19 04:11 UTC, jdmann submitted a review, later dismissed

2021-08-19 04:11 UTC, jdmann commented on routes/index.js
> +    res.status(418);
good status code

2021-08-19 04:11 UTC, jdmann commented on routes/orders.js
> +        if (req.user) {
might consider creating a protectedRoute middleware to make this more re-usable

2021-08-19 04:11 UTC, jdmann commented on routes/products.js
> +        next();
else next("error");

2021-08-19 04:11 UTC, jdmann commented on routes/products.js
> +        next();
otherwise this may result in a 404, which is not what you want to do, when handling the error

2021-08-19 04:11 UTC, jdmann commented on routes/products.js
> +        next();
next is only used for middleware, or handling an error

2021-08-19 04:11 UTC, jdmann commented on src/components/AllProducts.js
> +	const handleProducts = async () => {
perhaps this should be a useEffect to load the products when the component mounts?

2021-08-19 15:11 UTC, VW71superbeetle submitted a review, later dismissed

2021-08-19 16:24 UTC, roboMoose requested changes
Address comments from Jonathan and deploy your Dev branch by Saturday. 
Will do a quick review on Saturday before merging into main

2021-08-21 20:04 UTC, roboMoose approved these changes
1. make sure codebase clean and tidy.
2. create dummy data and populate db
3. register/login users.

2021-08-21 20:04 UTC, roboMoose commented on routes/users.js
> +            console.log("CreateUser Result==>>",user)
always remove logs!

2021-08-21 20:04 UTC, merged